### PR TITLE
fix common.urlJoin when target has query string

### LINKED ISSUE #2: common.urlJoin got unexpected result
```
const URL = require('url')
let common = require('http-proxy-node16/lib/http-proxy/common')
let targetPath = URL.parse('https://httpbin.org/redirect-to?url=https://httpbin.org/get').path
let outgoingPath = "/redirect"
console.log("urlJoin", common.urlJoin(targetPath, outgoingPath))
```

output:
```
urlJoin /redirect-to?url=https://httpbin.org/get/redirect
```

### PR DESCRIPTION
**Pull request by potoo0**
Close: #2

### CODE REVIEW

**Comment by Jimbly** [comment]
I'm unfamiliar with the workings of this library other than the one bug I fixed, but I guess I'm maintaining it now =).  What use case / problem in the public API does this fix?  Is this the same bug as https://github.com/http-party/node-http-proxy/pull/1334/files is fixing (and does that 1-line fix also fix your issue)?

**Comment by potoo0** [comment]
No, this commit actually fixed two bugs:
1. do not split url by `?`, because the query string may contain `?`, eg: `git.io/p1?a=a?1?2`
2. fix target path has query string, eg: `urlJoin('/p1?a=1', '/p2')` expected `/p1/p2?a=1`, but got `/p1?a=1/p2`

**Comment by Jimbly** [comment]
What use case / problem in the public API does this fix?  `urlJoin` isn't part of the public API, right?

**Comment by potoo0** [comment]
I built a gateway that depends on this proxy lib, an error occurs when the user-configured target contains query string.

---

For this particular proxy case, I will maintain it myself.

---

**case**
server:
```js
httpProxy.createProxyServer({target:'http://httpbin.org?token=123'}).listen(8000);
```

client:
```bash
curl http://localhost:8000/get
```

**Comment by Jimbly** [comment]
I'm happy to merge and publish it, just wanted to know what the use case was so I could at least do a quick test that nothing broke/it works =).

**Comment by potoo0** [comment]
Ok, close this pr if you don't think it's necessary.

**Comment by Jimbly** [comment]
Thanks!  Published to NPM as v1.0.4

**Pull request merged**
